alias l="ls -al --color"
alias ll="ls -la --color"
alias openproject="subl --project project.sublime-project"
alias vagrant_rebuild="vagrant destroy -f; vagrant up; vagrant ssh;"
alias c="clear"
alias test_install="python setup.py -p dev test_install"
alias open-project="subl --project"
